-- ==============================================================================
-- Migration: 001_initial_schema.sql
-- Description: Initial schema for Legal Metrology Packaged Commodity Compliance System
-- Database: PostgreSQL / Supabase
-- ==============================================================================

-- Enable UUID extension if not enabled (Supabase has pgcrypto / uuid-ossp enabled by default)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ------------------------------------------------------------------------------
-- 1. Table: rules
-- Purpose: Configurable compliance rules that the rule engine evaluates
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    field_name VARCHAR(100) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    validation_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'HIGH',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_rules_validation_type CHECK (
        validation_type IN ('PRESENT', 'NON_EMPTY', 'VALID_QUANTITY', 'VALID_PRICE', 'VALID_DATE', 'VALID_CONTACT')
    ),
    CONSTRAINT chk_rules_severity CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH')
    )
);

-- Indexes for rules table
CREATE INDEX IF NOT EXISTS idx_rules_rule_code ON rules(rule_code);
CREATE INDEX IF NOT EXISTS idx_rules_active ON rules(active);
CREATE INDEX IF NOT EXISTS idx_rules_field_name ON rules(field_name);

-- ------------------------------------------------------------------------------
-- 2. Table: inspections
-- Purpose: One product/package inspection record performed by an officer
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inspections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    image_url TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PROCESSING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_inspections_status CHECK (
        status IN ('PROCESSING', 'COMPLIANT', 'REVIEW', 'NON_COMPLIANT', 'ERROR')
    )
);

-- Indexes for inspections table
CREATE INDEX IF NOT EXISTS idx_inspections_status ON inspections(status);
CREATE INDEX IF NOT EXISTS idx_inspections_created_at ON inspections(created_at DESC);

-- ------------------------------------------------------------------------------
-- 3. Table: extracted_data
-- Purpose: Structured information extracted from the package image (1:1 with inspection)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS extracted_data (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inspection_id UUID UNIQUE NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
    product_name TEXT,
    manufacturer TEXT,
    net_quantity TEXT,
    mrp TEXT,
    date TEXT,
    consumer_care TEXT,
    extraction_confidence NUMERIC(5, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for extracted_data table
CREATE INDEX IF NOT EXISTS idx_extracted_data_inspection_id ON extracted_data(inspection_id);

-- ------------------------------------------------------------------------------
-- 4. Table: violations
-- Purpose: Individual compliance issues generated by the rule engine (1:many per inspection)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS violations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inspection_id UUID NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
    rule_id UUID NOT NULL REFERENCES rules(id) ON DELETE RESTRICT,
    field_name VARCHAR(100) NOT NULL,
    detected_value TEXT,
    status VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'HIGH',
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_violations_status CHECK (
        status IN ('FAIL', 'REVIEW')
    ),
    CONSTRAINT chk_violations_severity CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH')
    )
);

-- Indexes for violations table
CREATE INDEX IF NOT EXISTS idx_violations_inspection_id ON violations(inspection_id);
CREATE INDEX IF NOT EXISTS idx_violations_rule_id ON violations(rule_id);

-- ------------------------------------------------------------------------------
-- 5. Seed Prototype Rules
-- Note: These are initial prototype placeholder rules for backend architectural testing,
-- not an exhaustive or final legal metrology rulebook.
-- ------------------------------------------------------------------------------
INSERT INTO rules (rule_code, name, description, field_name, validation_type, required, severity, active)
VALUES
    (
        'LM001',
        'Manufacturer Name and Address Declaration',
        'Verifies that the name and complete address of the manufacturer/packer/importer is present on the package label.',
        'manufacturer',
        'PRESENT',
        TRUE,
        'HIGH',
        TRUE
    ),
    (
        'LM002',
        'Net Quantity Declaration and Standard Units',
        'Verifies that the net quantity is declared in standard units of weight or measure (e.g. g, kg, ml, l).',
        'net_quantity',
        'VALID_QUANTITY',
        TRUE,
        'HIGH',
        TRUE
    ),
    (
        'LM003',
        'Maximum Retail Price (MRP) Declaration',
        'Verifies that the retail sale price is declared in Indian Rupees (MRP inclusive of all taxes).',
        'mrp',
        'VALID_PRICE',
        TRUE,
        'HIGH',
        TRUE
    ),
    (
        'LM004',
        'Date of Manufacture/Packaging/Import',
        'Verifies that the month and year of manufacture or packaging is declared on the package.',
        'date',
        'VALID_DATE',
        TRUE,
        'MEDIUM',
        TRUE
    ),
    (
        'LM005',
        'Consumer Care Details Declaration',
        'Verifies that name, address, telephone number, and email address of person/office for consumer complaints is declared.',
        'consumer_care',
        'PRESENT',
        TRUE,
        'HIGH',
        TRUE
    )
ON CONFLICT (rule_code) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    field_name = EXCLUDED.field_name,
    validation_type = EXCLUDED.validation_type,
    required = EXCLUDED.required,
    severity = EXCLUDED.severity,
    active = EXCLUDED.active,
    updated_at = NOW();
